#Мб кому-то надо будет, обычный фикс фантомных блоков на сервере
#Я надеюсь, что оно работает, но по крайней мере рядом с поршнями должно + тротлинг есть
#Что-бы не забивать основной поток
#По всем вопросам писать мне в тг/ds - @teighto
#Бяк-БЯк-бЯк
#Для плагина нужна 21 или 25 JDK + работает на 1.20.x / 1.21.x / 26.x